[package]
name = "grib"
version = "0.1.0"
authors = ["Noritada Kobayashi <noritada.kobayashi@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
chrono="0.4"
pager="0.15"
console = "0.11"

[dev-dependencies]
xz2 = "0.1"
assert_cmd = "1.0.*"
predicates = "1.0.*"
tempfile = "3"
