name: "Feature request \U0001F4A1"
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Motivation
      description: A clear and concise description of what the motivation for the new feature is, and what problem it is solving.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      description: A clear and concise description of the feature you would like to add, and how it solves the motivating problem.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Any other context about the feature request.
